name: Branch Workflow
on:
  push:

jobs:
  create-pull-request:
    if: startsWith(github.event.ref, 'refs/head/app')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo ref
        run: echo ${{ github.event.ref }}
      - name: Create Pull Request
        run: gh pr create --draft --title "${{ github.event.head_commit.message }}" --body "${{ github.event.head_commit.message }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
