name: Branch Workflow
on:
  push:
    branches:
      - 'app/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        run: gh pr create --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
